### ISSUE TITLE
DMTN 13 and 14 HTML pages not available

### ISSUE THREAD

**Issue by migueldvb** [lsst-dm/dmtn-013#1]
The sphinx HTML output is not available in the page http://dmtn-013.lsst.io/latest/ that is linked from the README file in the repository.

**Comment by jonathansick** [comment]
Pim hasn't asked me to set up the technote deployment to the web yet. I can do so now if @pschella wants.

**Comment by jdswinbank** [comment]
They're available now. Closing this down.
